Module2 task1
htmlacademy-react/2053101-six-cities-simple-11 pull request #3
Opened 2022-10-26 09:19 UTC by lvktm

2022-10-26 09:55 UTC, AlexMasterov requested changes

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +  end: 6
Похоже на временный код.

[`Б 9`](https://up.htmlacademy.ru/react/11/criteries#b9)
> Для значений перечислений используется `CamelCase`

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/components/app/app.tsx
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/197991488-e5101c9c-15bd-4c4f-ab29-9fe35127633c.png)

</details>

<details>
<summary>Ожидание (markup/main.html)</summary>

![image](https://user-images.githubusercontent.com/700213/197991622-326d7927-4188-439d-839b-8a1a0842037f.png)

</details>

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/components/app/app.tsx
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/197991722-58b83a38-7ebb-400b-9290-bc95f9179ff1.png)

</details>

<details>
<summary>Ожидание (markup/main.html)</summary>

![image](https://user-images.githubusercontent.com/700213/197991797-7fe30882-6069-43e5-b68e-364bdad55389.png)

</details>

Нужно разделить слова пробелом.

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/components/app/app.tsx
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/197991953-7a37ab6f-3f9e-478a-a046-add5f4b21846.png)

</details>
<details>
<summary>Ожидание</summary>

![image](https://user-images.githubusercontent.com/700213/197992008-b7e533ff-eff7-4a20-82e8-c900d06a0653.png)

</details>

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +    <body className="page page--gray page--main">
```
Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.
```
> См. [Фрагменты](https://ru.reactjs.org/docs/fragments.html#short-syntax)

[`Б 2`](https://up.htmlacademy.ru/react/11/criteries#b2)
> При выполнении кода не возникает необработанных ошибок

2022-10-26 09:55 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +                Array.from({length: CardsCount.end}, Card)
```
Warning: Each child in a list should have a unique "key" prop.
```

Array.from({length: CardsCount.end}, `Card`)

React-компонент вызывается прямо в коде JSX, как простая функция. Похоже на временный код 🤔

> См. [Ключи](https://ru.reactjs.org/docs/lists-and-keys.html#keys)

[`Б 2`](https://up.htmlacademy.ru/react/11/criteries#b2)
> При выполнении кода не возникает необработанных ошибок

2022-10-26 12:48 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +    <React.Fragment>
https://github.com/htmlacademy-react/2053101-six-cities-simple-11/blob/42dbf5e17d88c7d2f36f21193be68d474507e9a3/project/src/pages/main/main.tsx#L3

Используй `<>`.

2022-10-26 12:49 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +      </head>
https://github.com/htmlacademy-react/2053101-six-cities-simple-11/blob/42dbf5e17d88c7d2f36f21193be68d474507e9a3/project/public/index.html#L27

Напомню, что React рендерится в узле с `#root` готового документа, где уже есть `header` и `body`.


См. https://github.com/htmlacademy-react/2053101-six-cities-simple-11/pull/3#discussion_r1005457577.

<details>
<summary>Проблема множится</summary>

```
Warning: validateDOMNesting(...): <head> cannot appear as a child of <div>.
Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.
```

![image](https://user-images.githubusercontent.com/700213/198029993-8239b241-be8c-4a18-8425-6dbf273ae0e8.png)

</details>

Сейчас в документе два узла `<header` и `<body>`, а специальный тег фрагмента от React `<>` использован неправильно.

Нужно разобраться и исправить разметку.

2022-10-26 12:53 UTC, AlexMasterov commented on project/src/pages/login/login.tsx
> +      </head>
```
Warning: validateDOMNesting(...): <head> cannot appear as a child of <div>.
Warning: validateDOMNesting(...): <body> cannot appear as a child of <div>.
```

<details>
<summary>pages/login/login.tsx</summary>

https://github.com/htmlacademy-react/2053101-six-cities-simple-11/blob/42dbf5e17d88c7d2f36f21193be68d474507e9a3/project/src/pages/login/login.tsx#L6-L12
</details>


Это нужно удалить.

2022-10-26 12:59 UTC, AlexMasterov commented on project/src/components/app/app.tsx
![image](https://user-images.githubusercontent.com/700213/198032110-00981d3b-cf8c-4908-8460-3c884157fef6.png)


Не исправлено.

2022-10-26 13:04 UTC, lvktm commented on project/src/pages/main/main.tsx
> +const cities: string[] = ['Paris', 'Cologne', 'Brussels', 'Amsterdam', 'Hamburg', 'Dusseldorf'];
as const добавлю, спасибо

"Названия констант (постоянных значений) написаны прописными (заглавными) буквами"
я руководствовался Б10
https://up.htmlacademy.ru/profession/react/10/react/11/criteries#b10

2022-10-26 13:10 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +const cities: string[] = ['Paris', 'Cologne', 'Brussels', 'Amsterdam', 'Hamburg', 'Dusseldorf'];
Код в примере критерия может не учитывать требования других критериев.

2022-10-26 20:42 UTC, lvktm commented on project/src/pages/main/main.tsx
> +const cities: string[] = ['Paris', 'Cologne', 'Brussels', 'Amsterdam', 'Hamburg', 'Dusseldorf'];
Надеюсь, правильно понял.
Запушил исправления.

2022-10-26 23:35 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +const City = {
<details>
<summary>pages/main/main.tsx</summary>

https://github.com/htmlacademy-react/2053101-six-cities-simple-11/blob/3d6fcba506fd780f2f5c78340fad2183d63c2883/project/src/pages/main/main.tsx#L5
https://github.com/htmlacademy-react/2053101-six-cities-simple-11/blob/3d6fcba506fd780f2f5c78340fad2183d63c2883/project/src/pages/main/main.tsx#L53
</details>

Непонятно, зачем было менять список на перечисление, если далее из его ключей снова получаем список 😃

В любом случае, следовало уточнить название:
```diff
- const City = { 
+ const PopularCity = { 
```

2022-10-26 23:35 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +                Object.values(City).map((element) => <Card value={element} key={element} />)
`Object.values(City)`.map((element) => <Card value={element} key={element} />)

**JS1/2**-Д22
> Массивы и объекты, содержимое которых вычисляется, собираются _один_ раз, а после этого **только переиспользуются**

Object.values(`City`).map((`element`) => <Card value={`element`} key={`element`} />)

1. Странная смена (потеря) смыслового контекста: `City` -> `element`;
2. Для общего именования элементов массива вне смыслового контекста предметной области еще с JS1 советовали использовать `item` вместо `element` (и `items` вместо `array`) , который при работе в окружение браузера может подразумевать DOM-элемент.

2022-10-26 23:36 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +const cities: string[] = ['Paris', 'Cologne', 'Brussels', 'Amsterdam', 'Hamburg', 'Dusseldorf'];
Да, отправляй на повторную проверку. Приму 😃

2022-10-26 23:40 UTC, AlexMasterov commented on project/src/components/card/card.tsx
> +    <li className="locations__item">
Непонятно, почему разметка с `locations__item` рендерится компонентом с названием `Card`. 

Разве это карточка 🤔

2022-10-27 11:13 UTC, lvktm commented on project/src/pages/main/main.tsx
> +const City = {
:eyes:

2022-10-27 11:15 UTC, merged

2022-10-27 11:16 UTC, lvktm commented on project/src/pages/main/main.tsx
> +                Object.values(City).map((element) => <Card value={element} key={element} />)
:eyes:

2022-10-27 11:22 UTC, lvktm commented on project/src/components/card/card.tsx
> +    <li className="locations__item">
![2022-10-27_142000](https://user-images.githubusercontent.com/101119183/198271244-2b71edaf-d1b6-4a68-92d3-8842e9f525cb.png)
Просто так было много слов "карточка", что решил также назвать компонент. Лучше LocationsItem?