Module4 task1
htmlacademy-react/2053101-six-cities-simple-11 pull request #5
Opened 2022-11-29 08:29 UTC by lvktm

2022-11-29 15:11 UTC, AlexMasterov requested changes

2022-11-29 15:11 UTC, AlexMasterov commented on project/src/mocks/const.ts
> +  five: [5, 'perfect'],
Такой объект не нужен.

> См. другое замечание по месту его использования

2022-11-29 15:11 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +                Object.values(PopularCity).map((city) => <Location value={city} key={city} />)
`Object.values(PopularCity)`

Желательно вычислить массив за пределами функций (компонентов), один раз, и _переиспользовать_ внутри. 

**JS1/2**-Д19
> Массивы и объекты, содержимое которых вычисляется, собираются один раз, а после этого только переиспользуются

2022-11-29 15:11 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
>  /* eslint-disable jsx-a11y/img-redundant-alt */
Нужно удалить.

2022-11-29 15:11 UTC, AlexMasterov commented on project/src/components/app/app.tsx
>            path="*"
Желательно `*` добавить в `AppRoute`.

2022-11-29 15:11 UTC, AlexMasterov commented on project/src/mocks/const.ts
> +
Нужно вынести `const.ts` из временной директории `mocks/`.

2022-11-29 15:15 UTC, AlexMasterov commented on project/src/components/offer-card-city/offer-card-city.tsx
> +
<details>
<summary>Сейчас</summary>

![image](https://user-images.githubusercontent.com/700213/204567834-bbd21049-09cd-4fbe-be1b-85641b724379.png)

</details>


<details>
<summary>Ожидание (markup/property.html)</summary>

![image](https://user-images.githubusercontent.com/700213/204567684-90876149-ff4a-4390-8104-8ce6846b90ae.png)

</details>

2022-11-29 18:09 UTC, lvktm commented on project/src/components/location/location.tsx
> +      <Link className={props.value === 'Amsterdam' ? 'locations__item-link tabs__item tabs__item--active' : 'locations__item-link tabs__item'} to="#">
👀

2022-11-29 18:10 UTC, lvktm commented on project/src/components/logo/logo.tsx
> +import { AppRoute } from '../../mocks/const';
👀

2022-11-29 18:12 UTC, lvktm commented on project/src/components/offer-card-city/offer-card-city.tsx
> +/* eslint-disable no-console */
👀

2022-11-29 18:15 UTC, lvktm commented on project/src/components/offer-card-city/offer-card-city.tsx
> +  const [, setOfferCardId] = useState('');
:eyes

2022-11-29 18:17 UTC, lvktm commented on project/src/components/offer-card/offer-card.tsx
> +        <Link to={propertyRoute}>
👀

2022-11-29 18:19 UTC, lvktm commented on project/src/components/offer-card/offer-card.tsx
> +    width: `${rating * ratingRatio}%`
:eyes

2022-11-29 18:20 UTC, lvktm commented on project/src/components/offer-card/offer-card.tsx
> +  const offerType = type[offerTypeLetter.first].toUpperCase() + type.slice(offerTypeLetter.other);
👀

2022-11-29 18:25 UTC, lvktm commented on project/src/components/offer-card/offer-card.tsx
> +/* eslint-disable jsx-a11y/img-redundant-alt */
👀

2022-11-29 18:26 UTC, lvktm commented on project/src/components/review/review.tsx
> +          Object.values(reviewRatingStar).map(([star, title]) => (
👀

2022-11-29 18:28 UTC, lvktm commented on project/src/components/review/review.tsx
> +                onInput={handleRadioButtonClick(star)}
То есть нужно передавать именно функцию? Нужно создать функцию, в параметрах которой evt?

2022-11-29 18:29 UTC, lvktm commented on project/src/components/review/review.tsx
> +                onInput={handleRadioButtonClick(star)}
👀

2022-11-29 18:29 UTC, lvktm commented on project/src/components/review/review.tsx
> +        onInput={handleTextAreaChange}
👀

2022-11-29 18:32 UTC, lvktm commented on project/src/mocks/const.ts
> +export const ratingRatio = 20;
👀

2022-11-29 18:32 UTC, lvktm commented on project/src/mocks/const.ts
> +  other: 1
👀

2022-11-29 18:32 UTC, lvktm commented on project/src/mocks/const.ts
> +  five: [5, 'perfect'],
👀

2022-11-29 18:35 UTC, lvktm commented on project/src/pages/main/main.tsx
> +                Object.values(PopularCity).map((city) => <Location value={city} key={city} />)
То есть лучше в создать отдельный компонент, который будет возвращать массив компонентов <Location />? Если да, то его оставить в модуле основного компонента или вынести в отдельный модуль?

2022-11-29 18:35 UTC, lvktm commented on project/src/pages/main/main.tsx
>  /* eslint-disable jsx-a11y/img-redundant-alt */
👀

2022-11-29 18:36 UTC, lvktm commented on project/src/components/app/app.tsx
>            path="*"
👀

2022-11-29 18:36 UTC, lvktm commented on project/src/mocks/const.ts
> +
👀

2022-11-29 18:38 UTC, lvktm commented on project/src/components/review/review.tsx
> +              title={`${title}`}
👀

2022-11-30 08:19 UTC, lvktm commented on project/src/pages/main/main.tsx
>  /* eslint-disable jsx-a11y/img-redundant-alt */
👀

2022-11-30 19:14 UTC, lvktm commented on project/src/components/offer-card/offer-card.tsx
> +        <Link to={propertyRoute}>
![2022-11-30_221228](https://user-images.githubusercontent.com/101119183/204887821-5aac924e-b903-4b2f-b0dd-8784b1ca29da.png)
Без двоеточия не получается сделать роутер.

2022-11-30 19:40 UTC, AlexMasterov commented on project/src/components/offer-card/offer-card.tsx
> +        <Link to={propertyRoute}>
`${AppRoute.Offer}/:id`

2022-11-30 20:29 UTC, lvktm commented on project/src/components/offer-card-city/offer-card-city.tsx
> +
👀

2022-11-30 20:41 UTC, AlexMasterov commented on project/src/pages/main/main.tsx
> +                Object.values(PopularCity).map((city) => <Location value={city} key={city} />)
```js
// вне компонента, можно даже в отдельном модуле
const POPULAR_CITIES = Object.values(PopularCity);
```

2022-11-30 22:26 UTC, AlexMasterov commented on project/src/components/review/review.tsx
> +                onInput={handleRadioButtonClick(star)}
Не совсем понятно, что ты в итоге хочешь сделать. Зачем тебе `evt`?

Скорее всего, ты хотел вызывать `handleRadioButtonClick` с разными значением `star`:
```js
onInput={() => handleRadioButtonClick(star)}
```

2022-12-01 18:36 UTC, AlexMasterov commented on project/src/components/offer-card-city/offer-card-city.tsx
> +      onMouseLeave={() => onHover(undefined)}
```diff
- onMouseLeave={() => onHover(undefined)}
+ onMouseLeave={() => onHover()}
```

2022-12-01 18:36 UTC, merged